---
title: "R Notebook"
output: html_notebook
---
```{r setup, include = FALSE}
library(ggplot2)
library(ggthemes)
library(readr)
library(stringr)
library(tidyr)
library(mosaic)
```

```{r}
filelist = list.files(pattern = "Brazil.*.csv")

#assuming tab separated values with a header    
datalist = lapply(filelist, function(x)read_csv(x))

#assuming the same header/columns for all files
datafr = do.call("rbind", datalist)
```

```{r}
names(datafr) <- c("Team", "Driver", "LapNumber","Compound", "Stint", "LapTime", "TyreLife", "FreshTyre", "TrackStatus", "IsAccurate")
datafr['LapTime'] = as.numeric(datafr$LapTime)/1000000
datafr <- filter(datafr, TrackStatus==1)
datafr <-  filter(datafr, IsAccurate==TRUE)
```

```{r}
model5 <- lm(LapTime ~ Team+Compound+LapNumber+, data=datafr)
summary(model5)
```

```{r}
TeamList = c("McLaren","Mercedes","Sauber","Toro Rosso","Haas F1 Team", "Renault", "Racing Point","Ferrari","Red Bull Racing","Williams")

mclaren <- filter(datafr, Team=="McLaren")
merc <- filter(datafr, Team=="Mercedes")
sauber <- filter(datafr, Team=="Sauber")
tororosso <- filter(datafr, Team=="Toro Rosso")
haas <- filter(datafr, Team=="Haas F1 Team")
renault <- filter(datafr, Team=="Renault")
racingpoint <- filter(datafr, Team=="Racing Point")
ferrari <- filter(datafr, Team=="Ferrari")
rbr <- filter(datafr, Team=="Red Bull Racing")
williams <- filter(datafr, Team=="Williams")

```

```{r}
plt <- ggplot(datafr, aes(TyreLife, LapTime))+geom_point()
plt + facet_wrap(~Driver,ncol=5)
```
```{r}
plt <- ggplot(mclaren, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(merc, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(sauber, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(tororosso, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(haas, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(renault, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(racingpoint, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(ferrari, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(rbr, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(williams, aes(TyreLife, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```


```{r}
plt <- ggplot(datafr, aes(LapNumber, LapTime))+geom_point()
plt + facet_wrap(~Driver,ncol=5)
```
```{r}
plt <- ggplot(mclaren, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(merc, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(sauber, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(tororosso, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(haas, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(renault, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(racingpoint, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(ferrari, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(rbr, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```
```{r}
plt <- ggplot(williams, aes(LapNumber, LapTime,color=Compound))+geom_point()+scale_color_manual(values=c("#FFFFFF", "#FFD318", "#FF2D2C")) + theme_excel()
plt + facet_wrap(~Driver,ncol=2)
```


